package compsciia;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GeneratorGUI extends javax.swing.JFrame {
    static String searchTrimester;
    static String excelLocation;
    static String sheetName;
    static String file;
    

    public GeneratorGUI() {
        System.out.println("RUNNING GENERATE GUI");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        helpMenuPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        endProgram = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fileName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sheetNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        T1checkBox = new javax.swing.JCheckBox();
        T2checkBox = new javax.swing.JCheckBox();
        T3checkBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        fileLocation = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        endProgram.setText("Close");
        endProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endProgramActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Please write the exact name of the excel file here (with extention):");

        fileName.setText("Excel file name here");
        fileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Please type in the exact sheet name that you want to use:");

        sheetNameTextField.setText("Sheet name");
        sheetNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sheetNameTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Select Trimester(Check one only):");

        T1checkBox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        T1checkBox.setText("Trimester 1");
        T1checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1checkBoxActionPerformed(evt);
            }
        });

        T2checkBox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        T2checkBox.setText("Trimester 2");
        T2checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2checkBoxActionPerformed(evt);
            }
        });

        T3checkBox.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        T3checkBox.setText("Trimester 3");
        T3checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T3checkBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Please copy and paste your excel file location here:");

        fileLocation.setText("Excel file location here");
        fileLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileLocationActionPerformed(evt);
            }
        });

        generateButton.setText("Generate!");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fileName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(endProgram)
                                .addGap(18, 18, 18)
                                .addComponent(generateButton)
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sheetNameTextField))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(fileLocation)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(T1checkBox)
                        .addGap(140, 140, 140)
                        .addComponent(T2checkBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(T3checkBox)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fileLocation))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sheetNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T1checkBox)
                    .addComponent(T2checkBox)
                    .addComponent(T3checkBox))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateButton)
                    .addComponent(endProgram))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        helpMenuPane.addTab("Input!", jPanel1);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Description of product:\n- This software, Student Portfolio Generator, will generate individual student portfolios using data from an excel file provided by user.\n\nUse:\n- In this window please input n all the fields:\n1. Excel file location address can be found in the view finder, copy and paste the address\n2. Excel file name must be identical, including extension. For example: SampelGradebook.xlsx\n3. Excel spreadsheet name must be identical with what is enetered in your file\n4. Please tick only 1 check box, if checked the wrong checkbox, please uncheck and then check the correct check box\n\nIf your are receiving errors, please check your inputs, otherwise, please check if your excel document is correctly formated.\nKeywords:\n-\t‘Trimester 1’, ‘Trimester 2’, ‘Trimester 3’\n-\tTest \n-\tFinal\nNote: Without quotation marks, meaning that it can be written in any form, for instance:\n-\tTest, TEST, test, TEst, TeST….\n\nImportant format:\n-\tThe name column must be in the same row as ‘Trimester X’\n-\tTitles must be placed right below the row where ‘Trimester X’ is\n-\tAll titles must be in line\n-\tNumber of students is best to be consistent in trimesters\n\t\tAdd student names with no grades if needed\n-\tFor now, the program only recognizes the cell style of percentage\n-\tFor now, the program only recognizes the cell type of numbers and string\n-\tBest effect to not use merge cells, but it will not bug the program\n-\tDo not have blank row between students\n\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1141, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
        );

        helpMenuPane.addTab("Help menu", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpMenuPane)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpMenuPane, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sheetNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sheetNameTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sheetNameTextFieldActionPerformed


    private void T1checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1checkBoxActionPerformed
        // TODO add your handling code here:
        searchTrimester = "Trimester 1";
    }//GEN-LAST:event_T1checkBoxActionPerformed

    private void T2checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2checkBoxActionPerformed
        // TODO add your handling code here:
        searchTrimester = "Trimester 2";
    }//GEN-LAST:event_T2checkBoxActionPerformed

    private void T3checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T3checkBoxActionPerformed
        // TODO add your handling code here:
        searchTrimester = "Trimester 3";
    }//GEN-LAST:event_T3checkBoxActionPerformed

    private void endProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endProgramActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_endProgramActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:

        file = fileName.getText();                                      //    Get text in the text field
        excelLocation = fileLocation.getText();
        sheetName = sheetNameTextField.getText();
        
        CompSciIA run = new CompSciIA();                    //     Class where the method 'run'  is
        
        try {
            run.run();                                                          //      Run all the procedures
        } catch (IOException ex) {
            Logger.getLogger(GeneratorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_generateButtonActionPerformed

    private void fileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fileNameActionPerformed

    private void fileLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileLocationActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_fileLocationActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
          //  java.util.logging.Logger.getLogger(fileName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
           // java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new GeneratorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox T1checkBox;
    private javax.swing.JCheckBox T2checkBox;
    private javax.swing.JCheckBox T3checkBox;
    private javax.swing.JButton endProgram;
    private javax.swing.JTextField fileLocation;
    private javax.swing.JTextField fileName;
    private javax.swing.JButton generateButton;
    private javax.swing.JTabbedPane helpMenuPane;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField sheetNameTextField;
    // End of variables declaration//GEN-END:variables
}
